In [ ]:
#importing libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [ ]:
#importing the dataset

dataset = pd.read_excel('Folds5x2_pp.xlsx')
dataset.head()

#AT = Temperature V = Exhaust Vacuum AP = Ambient Pressure  RH = Relative Humidity 
#PE = Net Hourly Electrical Energy Output 

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [ ]:
#checking for missing data
dataset.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

In [ ]:
# dependent and independent variables

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
#splitting dataset into train and test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Making the ANN

In [ ]:
#initialising the ANN

ann = tf.keras.models.Sequential()

In [ ]:
#adding the first hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
#adding the second hidden layer

ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [ ]:
#adding a third hidden layer

#ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [ ]:
#adding the output layer

ann.add(tf.keras.layers.Dense(units=1))

#no activation function for Regression

## Training the ANN

In [ ]:
#compiling the ANN

ann.compile(optimizer='adam', loss='mean_squared_error')

#we didnt choose the loss, binary_crossentropy because we arent dealing with a binary value

#for classification of binary output
#ann.compile(optimizer='adam', loss='binary_crossentropy', metrics = 'accuracy')

In [ ]:
#training the ANN model on the Training set

ann.fit(X_train, y_train, batch_size=32, epochs=100)

#with three hidden layers
#Epoch 100/100
#240/240 [==============================] - 0s 954us/step - loss: 27.1619

#with two hidden layers
#Epoch 100/100
#240/240 [==============================] - 0s 950us/step - loss: 26.4547

Epoch 1/100
240/240 [==============================] - 1s 977us/step - loss: 412790.9085
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 54055.7286
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 565.5441
Epoch 4/100
240/240 [==============================] - 0s 895us/step - loss: 274.2263
Epoch 5/100
240/240 [==============================] - 0s 920us/step - loss: 277.8064
Epoch 6/100
240/240 [==============================] - 0s 939us/step - loss: 269.6226
Epoch 7/100
240/240 [==============================] - 0s 941us/step - loss: 265.7590
Epoch 8/100
240/240 [==============================] - 0s 934us/step - loss: 262.6187
Epoch 9/100
240/240 [==============================] - 0s 943us/step - loss: 248.8300
Epoch 10/100
240/240 [==============================] - 0s 938us/step - loss: 252.8925
Epoch 11/100
240/240 [==============================] - 0s 948us/step - loss: 238.1960
Epoch 12/100
240/240 [=============================

In [ ]:
#predicting the results of the Test set

y_pred = ann.predict(X_test)
y_pred

array([[430.4942 ],
       [461.61325],
       [465.14786],
       ...,
       [472.3063 ],
       [439.26706],
       [458.40823]], dtype=float32)

In [ ]:
#checking accuracy 

from sklearn.metrics import r2_score
accuracy = r2_score(y_test, y_pred)


In [ ]:
accuracy

0.9140401736787663

In [ ]:
print('Accuracy is {:.2f}%'.format(accuracy*100))

Accuracy is 91.40%


In [ ]:
#predicting a value

#the real values with the answer
# 	AT 	V 	AP 	RH 	PE
# 	14.96 	41.76 	1024.07 	73.17 	463.26

y_predicted = ann.predict([[14.96, 41.76 ,1024.07, 73.17]])
print(y_predicted)

[[470.35303]]


In [ ]:
#difference of 1.08% from the real value

(y_predicted/463.26)*100

array([[101.53111]], dtype=float32)

In [ ]:
#comparing the y_pred values  of the test set to the real values
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[430.49 431.23]
 [461.61 460.01]
 [465.15 461.14]
 ...
 [472.31 473.26]
 [439.27 438.  ]
 [458.41 463.28]]
