##### Deep Learning is the most exciting and powerful branch of Machine Learning. Deep Learning models can be used for a variety of complex tasks:

    Artificial Neural Networks for Regression and Classification
    Convolutional Neural Networks for Computer Vision
    Recurrent Neural Networks for Time Series Analysis
    Self Organizing Maps for Feature Extraction
    Deep Boltzmann Machines for Recommendation Systems
    Auto Encoders for Recommendation Systems

# Artificial Neural Network

In [ ]:
#This helps train on Classification for a Binary Outcome

### Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
#checking for missing data 
dataset.describe()

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [ ]:
#creating variables
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
#male = 1, female = 0

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
#France = 100, Spain = 001, Germany = 010

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

### Feature Scaling

In [ ]:
#compulsory for deep learning irrespective if numbers have 1s and 0s already
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
#sc_y = StandardScaler() #no need for this
X_train = sc_X.fit_transform(X_train)
X_test = sc_y.transform(X_test)#we don't apply fit here in order to prevent information leakage

In [ ]:
print(X_train)

[[-0.99850112  1.71490137 -0.57273139 ... -1.55337352  0.97725852
   0.42739449]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352 -1.02327069
  -1.02548708]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.94479772]
 ...
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.14096853]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
   0.01781218]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017 -1.02327069
  -1.15822478]]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
#create a variable that is the neural network itself
#created as an object of a class called Sequential
#other types are Computational Graphs, neurons not connected in successive layers. Ex. Restricted or Deep Boltzmann's Machine
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
#Using the Dense Class
#.add is a method in the Dense Class
#Units = number of hidden neurons 
#how many hidden neurons should I choose? 
#these are hyperparameters which won't be trained during the process. Choose the right number
#of hidden parameters based on Experimentation. Using 6 in this task
#NB::this code is basically for the first hidden layer and not the input layer  
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
#same code as the first hidden layer
#you can manipulate the hyperparameters and activation functions and compare accuracy 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
#why didn't we choose 2 units for the output?
#this is because we are predicting a binary variable of 1/0. It has only one dimension
#if we were doing Classification with a non-binary dependent variable (ie dependent variable with 3 classes, we will need 3 dimensions)#HIGHER
#we will need to hot encode such dependent variables too
#better use a SIGMOID activation function for the output layer because it helps predict probability that output outcome is 1.
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
#when prediction more than two categories, activation should be SoftMax

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
#adam is a type of Stochastic Gradient Descent
#for Binary Classification, loss function must be binary_crossentropy
#for Non-Binary Classification, loss must be categorical_crossentropy
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs = 100)
#using Batch Gradient Descent

Epoch 1/100
250/250 [==============================] - 1s 969us/step - loss: 0.6766 - accuracy: 0.5474
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4732 - accuracy: 0.8027
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4456 - accuracy: 0.7986
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4257 - accuracy: 0.8080
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4020 - accuracy: 0.8208
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4053 - accuracy: 0.8172
Epoch 7/100
250/250 [==============================] - 0s 982us/step - loss: 0.3773 - accuracy: 0.8256
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3815 - accuracy: 0.8267
Epoch 9/100
250/250 [==============================] - 0s 985us/step - loss: 0.3691 - accuracy: 0.8264
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3677 - 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation



Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [ ]:
ann.predict(sc_X.transform([[1, 0, 0, 600, 1,40,3,60000,2,1,1,50000]]))
#OR to get answer in probabilty form
#ann.predict(sc_X.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5


array([[0.01990062]], dtype=float32)

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
#we want to return 1s and 0s so we can concatenate
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1527   58]
 [ 213  202]]


0.8645